### ISSUE TITLE
fpermissive invalid conversion from ‘const void*’ to ‘void*'

### ISSUE THREAD

**Issue by barquetta** [ihedvall/utillib#7]
https://github.com/ihedvall/utillib/blob/79fc951b6c7dfe9e36a0b0fc900afa04e67c6dd8/src/listenmessage.cpp#L33

I encountered an issue while using the memcpy that handles boost endian_buffer data. When attempting to use the function, the compiler throws an error: "invalid conversion from 'const void*' to 'void*'" [-fpermissive]. This error occurs because data() function on endian_buffer returns a constant pointer. It should be used just for read. My boost version is 1.71.0
I solved just by casting char const * to char* with const_cast.

The behavior is exactly the same also for other memcpy involving endian_buffer.

O.S. Ubuntu 20.04.4 LTS
g++-10 version 10.3.0
gcc-10 version 10.3.0

**Comment by ihedvall** [comment]
The problem seems to be solved in boost version 1.72.0 (see below). It can be solved in 2 ways. The automatic build uses 1.74.0 while I'm using 1.81.0.

Solution A or B?
A: Upgrade the boost library.
B: Change the code.
 
Changes in 1.72.0
    Made endian_reverse, conditional_reverse and *_to_* constexpr on GCC and Clang
    Added convenience load and store functions
    Added floating point convenience typedefs
    _**Added a non-const overload of data(); changed its return type to unsigned char**_
    Added __int128 support to endian_reverse when available
    Added a convenience header boost/endian.hpp

Changes in 1.71.0
    Clarified requirements on the value type template parameter
    Added support for float and double to endian_buffer and endian_arithmetic
    Added endian_load, endian_store
    Updated endian_reverse to correctly support all non-bool integral types
    Moved deprecated names to the deprecated header endian.hpp

**Comment by bruno15** [comment]
Solution 2 think it's better :)

**Comment by ihedvall** [comment]
It's a day work to setup a build machine with Linux and boost 1.71.0, so I added you as collaborator to the repository.

**Comment by ihedvall** [comment]
Just to inform you, that const_cast would not work in newer versions of boost as the data() function now returns a unsigned char* pointer, not a char*. I'm trying with reiinterpret_cast instead.

**Comment by ihedvall** [comment]
I want to use the same source file for boost 1.71 and 1.8x. Well reinterpret_cast doesn't work either so....

**Comment by ihedvall** [comment]
First static_cast to const void* then the const_cast to void*

**Comment by bruno15** [comment]
make sense!

**Comment by bruno15** [comment]
Tested and it works perfectly on Linux.
